#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

feh --bg-fill ~/.config/wallpaper &
polybar main &
picom --experimental-backends &

#Replace eDP-1 with the name of your main display
bspc monitor eDP-1 -d "1" "2" "3" "4"

bspc config normal_border_color  "#f47c7c"
bspc config active_border_color  "#ffffff"
bspc config focused_border_color "#ffffff"

bspc config border_width         3
bspc config window_gap           20

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
